Repository wecode-bootcamp-korea/Wesop-frontend, pull requests merged in 2021-01, with the labels that each got.

#4 [16기 김희진] 메인 페이지 - 슬라이더 컴포넌트 구현
  package-lock.json
  package.json
  public/Data/MainSliderProducts.json
  src/Pages/Main/Component/Location.js
  src/Pages/Main/Component/Location.scss
  src/Pages/Main/Component/MainHeader.js
  src/Pages/Main/Component/MainHeader.scss
  src/Pages/Main/Component/NewProduct.js
  src/Pages/Main/Component/NewProduct.scss
  src/Pages/Main/Component/Products.js
  src/Pages/Main/Component/Products.scss
  src/Pages/Main/Component/Quote.js
  src/Pages/Main/Component/Quote.scss
  src/Pages/Main/Component/Slider.js
  src/Pages/Main/Component/Slider.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
  src/Pages/Main/MainSlider.js
  src/Pages/Main/MainSlider.scss
Labels: Status: 추가 기능 구현중

#6 [16기 김희진] ProductList 브랜치 생성 및 ProductList 페이지 레이아웃 구현/ 백엔드 데이터 통신 성공
  src/Pages/ProductList/Components/ProductListContent.js
  src/Pages/ProductList/Components/ProductListContent.scss
  src/Pages/ProductList/Components/ProductListHeader.js
  src/Pages/ProductList/Components/ProductListHeader.scss
  src/Pages/ProductList/Components/ProductListHowTo.js
  src/Pages/ProductList/Components/ProductListHowTo.scss
  src/Pages/ProductList/Components/ProductListNextStep.js
  src/Pages/ProductList/Components/ProductListNextStep.scss
  src/Pages/ProductList/Components/ProductListSubNav.js
  src/Pages/ProductList/Components/ProductListSubNav.scss
  src/Pages/ProductList/ProductList.js
  src/Pages/ProductList/ProductList.scss
  src/config.js
Labels: Status: 리뷰 요청, Status: 추가 기능 구현중

#1 [16기 태성현] Add: feature/NavList Nav 제품보기 부분 생성
  src/Components/Nav/CategoryMenu/CategoryMenu.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavList/NavCategoryList/NavCategoryList.js
  src/Components/Nav/NavList/NavCategoryList/NavCategoryList.scss
  src/Components/Nav/NavList/NavList.js
  src/Components/Nav/NavList/NavList.scss
  src/Components/Nav/NavList/NavProductList/NavProductList.js
  src/Components/Nav/NavList/NavProductList/NavProductList.scss
  src/Components/Nav/NavList/PropertyData.js
  src/Routes.js
  src/Styles/common.scss
  src/config.js
Labels: Status: Accepted

#7 [16기 태성현] Feature/product detail 제품상세 페이지 백엔드와 연결완료 / 동적라우팅 구현중
  src/Pages/CategoryList/CategoryList.js
  src/Pages/Main/Main.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductInfo/ProductInfo.js
  src/Pages/ProductDetail/ProductInfo/ProductInfo.scss
  src/Pages/ProductDetail/ProductInstruction/ProductInstruction.js
  src/Pages/ProductDetail/ProductInstruction/ProductInstruction.scss
  src/Routes.js
  src/Styles/reset.scss
  src/config.js
Labels: Status: Accepted

#3 [16기 이필제] Feature/Nav
  .gitignore
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Login/Login.scss
  src/Components/Nav/Nav.js
  src/Pages/Main/Main.scss
  src/index.js
Labels: Status: Accepted

#2 [16기 이필제] Feature/Login Add: 컴포넌트별 기능 구현
  package-lock.json
  package.json
  src/Components/Nav/Login/DefaultForm/DefaultForm.js
  src/Components/Nav/Login/DefaultForm/DefaultForm.scss
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Login/Login.scss
  src/Components/Nav/Login/SignInForm/SignInForm.js
  src/Components/Nav/Login/SignInForm/SignInForm.scss
  src/Components/Nav/Login/SignUpForm/SignUpForm.js
  src/Components/Nav/Login/SignUpForm/SignUpForm.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
Labels: Status: 리뷰 진행중

#9 [16기 태성현] feature/routing Modify: 제품 리스트 -> 제품상세 동적라우팅 적용
  src/Components/Footer/Footer.js
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavList/NavCategoryList/NavCategoryList.js
  src/Components/Nav/NavList/NavList.js
  src/Components/Nav/NavList/NavProductList/NavProductList.js
  src/Components/Nav/NavList/NavProductList/NavProductList.scss
  src/Pages/Main/Component/Location.js
  src/Pages/Main/Component/MainHeader.js
  src/Pages/Main/Component/Slider.js
  src/Pages/ProductDetail/ProductDetail.js
  src/Pages/ProductDetail/ProductDetail.scss
  src/Pages/ProductDetail/ProductInstruction/ProductInstruction.js
  src/Pages/ProductList/Components/ProductListContent.js
  src/Pages/ProductList/Components/ProductListContent.scss
  src/Pages/ProductList/Components/ProductListSubNav.js
  src/Routes.js
  src/config.js
Labels: Status: 리뷰 요청

#11 [16기 이필제] feature/login "Modify:구조분해할당작업"
  src/Components/Nav/Login/DefaultForm/DefaultForm.js
  src/Components/Nav/Login/DefaultForm/DefaultForm.scss
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Login/SignInForm/SignInForm.js
  src/Components/Nav/Login/SignInForm/SignInForm.scss
  src/Components/Nav/Login/SignUpForm/SignUpForm.js
  src/Components/Nav/Login/SignUpForm/SignUpForm.scss
Labels: Status: 리뷰 요청

#12 [16기 태성현] Modify: NavList 스테이트, 함수 Nav바로 옮김/NavList 슬라이드 애니메이션 추가
  src/Components/Nav/Login/Login.scss
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavList/NavList.js
  src/Components/Nav/NavList/NavList.scss
  src/Pages/ProductDetail/ProductDetail.js
Labels: Status: 리뷰 요청

#13 [16기 태성현] Modify: 수정
  src/Components/Nav/Nav.js
  src/Components/Nav/Nav.scss
  src/Components/Nav/NavList/NavCategoryList/NavCategoryList.js
  src/Components/Nav/NavList/NavCategoryList/NavCategoryList.scss
  src/Components/Nav/NavList/NavList.js
Labels: Status: Accepted

#8 [16기 김희진] refactor/main 브랜치 생성 및 코드 리팩토링 중
  package-lock.json
  package.json
  src/Components/Nav/Nav.scss
  src/Pages/Main/Component/Location.js
  src/Pages/Main/Component/Location.scss
  src/Pages/Main/Component/MainHeader.js
  src/Pages/Main/Component/MainHeader.scss
  src/Pages/Main/Component/NewProduct.js
  src/Pages/Main/Component/NewProduct.scss
  src/Pages/Main/Component/Products.js
  src/Pages/Main/Component/Products.scss
  src/Pages/Main/Component/Quote.scss
  src/Pages/Main/Component/Slider.js
  src/Pages/Main/Component/Slider.scss
  src/Pages/Main/Main.js
  src/Pages/Main/Main.scss
Labels: Status: Accepted

#10 [16기 김희진] refactor/product_list 브랜치 생성 및 코드 리팩토링 중
  debug.log
  src/Components/Footer/Footer.js
  src/Components/Footer/Footer.scss
  src/Components/Nav/NavList/NavList.js
  src/Components/Nav/NavList/NavList.scss
  src/Pages/Main/Component/Location.scss
  src/Pages/Main/Component/MainHeader.scss
  src/Pages/Main/Component/NewProduct.scss
  src/Pages/Main/Component/Slider.js
  src/Pages/Main/Main.js
  src/Pages/ProductList/Components/ProductListContent.js
  src/Pages/ProductList/Components/ProductListContent.scss
  src/Pages/ProductList/Components/ProductListHeader.scss
  src/Pages/ProductList/Components/ProductListHowTo.js
  src/Pages/ProductList/Components/ProductListHowTo.scss
  src/Pages/ProductList/Components/ProductListNextStep.js
  src/Pages/ProductList/Components/ProductListNextStep.scss
  src/Pages/ProductList/Components/ProductListSubNav.js
  src/Pages/ProductList/Components/ProductListSubNav.scss
  src/Pages/ProductList/ProductList.js
  src/config.js
Labels: Status: 추가 기능 구현중

#14 [16기 이필제] feature/Login Modiy: Back버튼기능 추가중, 최종작업중
  src/Components/Nav/Login/DefaultForm/DefaultForm.js
  src/Components/Nav/Login/Login.js
  src/Components/Nav/Login/Login.scss
  src/Components/Nav/Login/SignInForm/SignInForm.js
  src/Components/Nav/Login/SignUpForm/SignUpForm.js
  src/Components/Nav/Nav.scss
  src/index.js
Labels: Status: Accepted
